version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: demo-test
      MYSQL_USER: akash
      MYSQL_PASSWORD: password
    ports:
      - "7054:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "9000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=akash
      - PMA_PASSWORD=password
  
  # zipkin:
  #   image: openzipkin/zipkin-slim
  #   restart: always
  #   ports:
  #     - "9411:9411"
    